

EN_VOICE_MALE = "en-GB-RyanNeural"
EN_VOICE_FEMALE = "en-GB-SoniaNeural"
VN_VOICE_MALE = "vi-VN-NamMinhNeural"
VN_VOICE_FEMALE = "vi-VN-HoaiMyNeural"
GOOGLE_VOICE_MALE = "GOOGLE_VOICE_MALE"
GOOGLE_VOICE_FEMALE = "GOOGLE_VOICE_FEMALE"